# Config file for pact http server. Launch with `pact -s config.yaml`

# HTTP server port
port: 8085

# directory for HTTP logs
logDir: myLog

# persistence directory
persistDir: myLog

# SQLite pragmas for pact back-end
pragmas: []

# verbose: provide log output
verbose: True