{
 "title": "Nuchain Cluster Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Cluster Size",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "max(nuchain_cluster_size)" }
   ]
  },
  {
   "title": "Cluster Available",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(nuchain_cluster_available_size)"
    }
   ]
  },
  {
   "title": "Txs Processed",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(nuchain_consensus_commit_index)"
    }
   ]
  },
  {
   "title": "Available Cores",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "expr": "max(ghc_conc_num_processors)" }
   ]
  },
  {
   "title": "Term",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "max(nuchain_consensus_term)" }
   ]
  },
  {
   "title": "Quorum Size",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(nuchain_cluster_quorum_size)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "format": "deckbytes",
   "valueName": "current",
   "targets": [
    { "expr": "avg(process_memory_kb)" }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "expr": "avg(cpu_load1)" }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cpu_load1" }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nuchain_consensus_commit_index[5s])"
    }
   ]
  }
 ]
}